### ISSUE TITLE
Putting items in anvil causes crash

### ISSUE THREAD

**Issue by CyrusRevaine** [fxmorin/WeirdAddons#9]
While the rule anvilColorFormatting is true, putting items in an anvil causes a crash.
[crash-2022-05-10_17.02.25-client.txt](https://github.com/fxmorin/WeirdAddons/files/8664961/crash-2022-05-10_17.02.25-client.txt)

**Comment by FxMorin** [comment]
Fixed version: https://github.com/fxmorin/WeirdAddons/suites/6457748320/artifacts/236902966
